"""
database/models.py
==================
Pydantic models that define the schema for MongoDB documents.

These serve three roles:
1. Validate data before insertion (catches bad types early).
2. Serialise documents for FastAPI responses (via .dict() / .json()).
3. Act as documentation — the schema is explicit and typed.

OCR result document structure
------------------------------
{
    "_id":        ObjectId (auto-generated by MongoDB),
    "filename":   str,
    "text":       str,
    "length":     int,
    "confidence": float,
    "status":     str,          # "success" | "no_detection" | "no_text" | "error"
    "timestamp":  datetime (UTC)
}
"""

from datetime import datetime, timezone
from typing import Optional

from pydantic import BaseModel, Field


class OCRDocument(BaseModel):
    """
    Schema for a single OCR result stored in MongoDB.

    ``id`` maps to MongoDB's ``_id`` field.
    All fields except ``id`` are required at insertion time.
    """
    id: Optional[str] = Field(default=None, alias="_id")
    filename: str
    text: str
    length: int
    confidence: float
    status: str = "success"
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = {
        "populate_by_name": True,   # allow both 'id' and '_id'
        "json_encoders": {
            datetime: lambda v: v.isoformat(),
        },
    }

    def to_mongo(self) -> dict:
        """Return a dict suitable for MongoDB insertion (no 'id' key)."""
        data = self.model_dump(exclude={"id"}, by_alias=False)
        return data


class OCRDocumentOut(BaseModel):
    """
    Response model returned by FastAPI endpoints.

    Converts MongoDB's ObjectId to a plain string and exposes a clean
    JSON structure to the frontend.
    """
    id: str = Field(alias="_id")
    filename: str
    text: str
    length: int
    confidence: float
    status: str
    timestamp: datetime

    model_config = {
        "populate_by_name": True,
        "json_encoders": {datetime: lambda v: v.isoformat()},
    }
